### ISSUE TITLE
Infografía gestión de proyectos de software

### ISSUE THREAD

**Issue by JeserLeonel** [SistemasTecTlaxiaco/infografia-JeserLeonel-1#2]
![GESTIÓN DE PROYECTOS DE SOFTWARE](https://user-images.githubusercontent.com/79876847/132154873-63f1f8ea-f43d-40b8-9146-1d38b5e38872.jpg)

**Comment by Eva155** [comment]
Calificación: 20 PUNTOS 
Calificó: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Bien hecho y revisado
